name: my First workflow 

on:
  workflow_run:
    workflows: [ "manual" ]
    types: [ completed ]

  workflow_dispatch:
    inputs:
       port:
          description: Neeeded
          type: string
          required: true
          default: dffd

       name:
          description: can give anything
          type: string
          required: true
          default: dinesh

    
          

jobs:
    echo-input:
      runs-on: ubuntu-latest
      if: |
       github.event_name == 'workflow_dispatch' ||
       (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')

      env: 
        port: ${{ inputs.port   || 'dffd' }}
        name: ${{ inputs.name   || 'dinesh' }}

      steps: 
        - name: running-second-job
          run: |
           echo  "port : $port"
           echo "name : $name"  
