name: my First workflow 

on:
 workflow_dispatch:
    inputs:
       port:
          description: Neeeded
          type: string
          required: true
          default: dffd

       name:
          description: can give anything
          type: string
          required: true
          default: dinesh

 workflow_call:
    inputs:
       port:
          description: Neeeded
          type: string 
          default: erer

       name:
          description: can give anything 
          type: string
          default: dinesh    
          

jobs:
    echo-input:
      runs-on: ubuntu-latest
      steps: 
         - name: echo given input 
           run: |
               echo "Hi Hello ...... ${{github.event.inputs.port}}  ${{github.event.inputs.name}}"     
